# This is where the countries get seeded.
module Seed
	module Shared
		class Countries

			# They're all class level methods
			class << self

				# Countries
				def seed
					puts "Seeding all countries..."
					[ ['Afghanistan', 'AF', 'AFG', '؋'],
						['Albania', 'AL', 'ALB', 'Lek'],
						['Algeria', 'DZ', 'DZA', 'DZD'],
						['Andorra', 'AD', 'AND', '€'],
						['Angola', 'AO', 'AGO', 'ƒ'],
						['Antigua and Barbuda', 'AG', 'ATG', '$'],
					  ['Argentina', 'AR', 'ARG', '$'],
					  ['Armenia', 'AM', 'ARM', 'Lek'],
					  ['Australia', 'AU', 'AUS', '$'], 
					  ['Austria', 'AT', 'AUT', '€'],
					  ['Azerbaijan', 'AZ', 'AZE', 'ман'],
					  ['Bahamas', 'BS', 'BHS', '$'],
					  ['Bahrain', 'BH', 'BHR', 'د.ب'],
					  ['Bangladesh', 'BD', 'BGD', '$'],
					  ['Barbados', 'BB', 'BRB', '$'],
					  ['Belarus', 'BY', 'BLR', 'p.'],
					  ['Belgium', 'BE', 'BEL', '€'],
					  ['Belize', 'BZ', 'BLZ', 'BZ$'],
					  ['Benin', 'BJ', 'BEN', '$'],
					  ['Bhutan', 'BT', 'BTN', '$'],
					  ['Bolivia (Plurinational State of)', 'BO', 'BOL', '$b'],
					  ['Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 'ƒ'],
					  ['Bosnia and Herzegovina', 'BA', 'BIH', 'KM'],
					  ['Botswana', 'BW', 'BWA', 'P'],
					  ['Brazil', 'BR', 'BRA', '$' ],
					  ['Brunei Darussalam', 'BN', 'BRN', '$'],
					  ['Bulgaria', 'BG', 'BGR', 'лв'],
					  ['Burkina Faso', 'BF', 'BFA', '$'],
					  ['Burundi', 'BI', 'BDI', 'лв'],
					  ['Cabo Verde', 'CV', 'CPV', '$'],
					  ['Cambodia', 'KH', 'KHM', '៛'],
					  ['Cameroon', 'CM', 'CMR', '₫'],
					  ['Canada', 'CA', 'CAN', 'CA$'],
					  ['Central African Republic', 'CF', 'CAF', '₫'],
					  ['Chad', 'TD', 'TCD', '₫'],
					  ['Chile', 'CL', 'CHL', '$'],
					  ['China', 'CN', 'CHN', '¥'],
					  ['Colombia', 'CO', 'COL', '$'],
					  ['Comoros', 'KM', 'COM', 'CF'],
					  ['Congo', 'CG', 'COG', '₫'],
					  ['Congo (Democratic Republic of)', 'CD', 'COD', '₫'],
					  ['Costa Rica', 'CR', 'CRI', '₡'],
					  ['Côte d\'Ivoire', 'CI', 'CIV', '₡'],
					  ['Croatia', 'HR', 'HRV', 'kuna'],
					  ['Cuba', 'CU', 'CUB', '₱'],
					  ['Cyprus', 'CY', 'CYP', '€'],
					  ['Czech Republic', 'CZ', 'CZE', 'Kč'],
					  ['Denmark', 'DK', 'DNK', 'kr'],
					  ['Djibouti', 'DJ', 'DJI', 'Kč'],
					  ['Dominica', 'DM', 'DMA', '$'],
					  ['Dominican Republic', 'DO', 'DOM', 'RD$'],
					  ['Ecuador', 'EC', 'ECU', 'RD$'],
					  ['Egypt', 'EG', 'EGY', '£'],
					  ['El Salvador', 'SV', 'SLV', '$'],
					  ['Equatorial Guinea', 'GQ', 'GNQ', '₫'],
					  ['Eritrea', 'ER', 'ERI', '£'],
					  ['Estonia', 'EE', 'EST', '€'],
					  ['Ethiopia', 'ET', 'ETH', '£'],
					  ['Fiji', 'FJ', 'FJI', '$'],
					  ['Finland', 'FI', 'FIN', '€'],
					  ['France', 'FR', 'FRA', '€'],
					  ['Gambia', 'GM', 'GMB', '£'],
					  ['Gabon', 'GA', 'GAB', '₫'],
					  ['Georgia', 'GE', 'GEO', '£'],
					  ['Germany', 'DE', 'DEU', '€'],
					  ['Ghana', 'GH', 'GHA', '¢'],
					  ['Gibraltar', 'GI', 'GIB', '£'],
					  ['Greece', 'GR', 'GRC', '€'],
					  ['Greenland', 'GL', 'GRL', 'kr'],
					  ['Grenada', 'GD', 'GRD', '$'],
					  ['Guatemala', 'GT', 'GTM', 'Q'],
					  ['Guinea', 'GN', 'GIN', '£'],
					  ['Guinea-Bissau', 'GW', 'GNB', 'Q'],
					  ['Guyana', 'GY', 'GUY', '$'],
					  ['Haiti', 'HT', 'HTI', 'kn'],
					  ['Honduras', 'HN', 'HND', 'L'],
					  ['Hungary', 'HU', 'HUN', 'Ft'],
					  ['Iceland', 'IS', 'ISL', 'kr'],
					  ['India', 'IN', 'IND', '₹'],
					  ['Indonesia', 'ID', 'IDN', 'Rp'],
					  ['Iran (Islamic Republic of)', 'IR', 'IRN', '﷼'],
					  ['Iraq', 'IO', 'IRQ', '₹'],
					  ['Ireland', 'IE', 'IRL', '€'],
					  ['Israel', 'IL', 'ISR', '₪'],
					  ['Italy', 'IT', 'ITA', '€'],
					  ['Jamaica', 'JM', 'JAM', 'J$'],
					  ['Japan', 'JP', 'JPN', '¥'],
					  ['Jordan', 'JO', 'JOR', 'J$'],
					  ['Kazakhstan', 'KZ', 'KAZ', 'лв'],
					  ['Kenya', 'KE', 'KEN', 'KSh'],
					  ['Kiribati', 'KI', 'KIR', '$'],
					  ['Korea (Democratic People\'s Republic Of)', 'KP', 'PRK', '₩'],
					  ['Korea (Republic of)', 'KR', 'KOR', '₩'],
					  ['Kuwait', 'KW', 'KWT', '₩'],
					  ['Kyrgyzstan', 'KG', 'KGZ', 'лв'],
					  ['Laos', 'LA', 'LAO', '₭'],
					  ['Latvia', 'LV', 'LVA', 'Ls'],
					  ['Lebanon', 'LB', 'LBN', '£'],
					  ['Lesotho', 'LS', 'LSO', '$'],
					  ['Liberia', 'LR', 'LBR', '$'],
					  ['Libya', 'LY', 'LBY', 'Ls'],
					  ['Liechtenstein', 'LI', 'LIE', 'CHF'],
					  ['Lithuania', 'LT', 'LTU', 'Lt'],
					  ['Luxembourg', 'LU', 'LUX', '€'],
					  ['Macedonia', 'MK', 'MKD', 'ден'],
					  ['Madagascar', 'MG', 'MDG', 'Ls'],
					  ['Malawi', 'MW', 'MWI', '₨'],
					  ['Malaysia', 'MY', 'MYS', 'RM'],
					  ['Maldives', 'MV', 'MDV', '₨'],
					  ['Mali', 'ML', 'MLI', '$'],
					  ['Malta', 'MT', 'MLT', '€'],
					  ['Marshall Islands', 'MH', 'MHL', '$'],
					  ['Mauritania', 'MR', 'MRT', '₮'],
					  ['Mauritius', 'MU', 'MUS', '₨'],
					  ['Mexico', 'MX', 'MEX', '$'],
					  ['Micronesia (Federated States of)', 'FM', 'FSM', '$'],
					  ['Moldova', 'MD', 'MDA', 'L'],
					  ['Monaco', 'MC', 'MCO', '€'],
					  ['Mongolia', 'MN', 'MNG', '₮'],
					  ['Montenegro', 'ME', 'MNE', '€'],
					  ['Morocco', 'MA', 'MAR', 'Ls'],
					  ['Mozambique', 'MZ', 'MOZ', 'MT'],
					  ['Myanmar', 'MM', 'MMR', 'ден'],
					  ['Namibia', 'NA', 'NAM', '$'],
					  ['Nauru', 'NR', 'NRU', '$'],
					  ['Nepal', 'NP', 'NPL', '₨'],
					  ['Netherlands', 'NL', 'NLD', '€'],
					  ['New Zealand', 'NZ', 'NZL', '$'],
					  ['Nicaragua', 'NI', 'NIC', 'C$'],
					  ['Niger', 'NE', 'NER', '$'],
					  ['Nigeria', 'NG', 'NGA', '₦'],
					  ['Norway', 'NW', 'NOR', 'kr'],
					  ['Oman', 'OM', 'OMN', '﷼'],
					  ['Pakistan', 'PK', 'PAK', '₨'],
					  ['Palau', 'PW', 'PLW', '$'],
					  ['Palestine (State of)', 'PS', 'PSE', '$'],
					  ['Panama', 'PA', 'PAN', 'B/.'],
					  ['Papua New Guinea', 'PG', 'PNG', 'S./'],
					  ['Paraguay', 'PY', 'PRY', 'Gs'],
					  ['Peru', 'PE', 'PER', 'S/.'],
					  ['Philippines', 'PH', 'PHL', '₱'],
					  ['Poland', 'PL', 'POL', 'zł'],
					  ['Portugal', 'PT', 'PRT', '€'],
					  ['Qatar', 'QA', 'QAT', '﷼'],
					  ['Romania', 'RO', 'ROU', 'lei'],
					  ['Russia', 'RU', 'RUS', 'руб'],
					  ['Rwanda', 'RW', 'RWA', 'R₣'],
					  ['Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '£'],
					  ['Saint Kitts and Nevis', 'KN', 'KNA', '$'],
					  ['Saint Lucia', 'LC', 'LCA', '$'],
					  ['Saint Vincent and the Grenadines', 'VC', 'VCT', '$'],
					  ['Samoa', 'WS', 'WSM', '₫'],
					  ['San Marino', 'SM', 'SMR', '€'],
					  ['Sao Tome and Principe', 'ST', 'STP', '$'],
					  ['Saudi Arabia', 'SA', 'SAU', '﷼'],
					  ['Senegal', 'SN', 'SEN', '$'],
					  ['Serbia', 'RS', 'SRB', 'Дин.'],
					  ['Seychelles', 'SC', 'SYC', '₨'],
					  ['Sierra Leone', 'SL', 'SLE', '£'],
					  ['Singapore', 'SG', 'SGP', '$'],
					  ['Slovakia', 'SK', 'SVK', '€'],
					  ['Slovenia', 'SI', 'SVN', '€'],
					  ['Solomon Islands', 'SB', 'SLB', '$'],
					  ['Somalia', 'SO', 'SOM', 'S'],
					  ['South Africa', 'ZA', 'ZAF', 'R'],
					  ['South Sudan', 'SS', 'SSD', '$'],
					  ['Spain', 'ES', 'ESP', '€'],
					  ['Sri Lanka', 'LK', 'LKA', '₨'],
					  ['Sudan', 'SD', 'SDN', '₨'],
					  ['Suriname', 'SR', 'SUR', '$'],
					  ['Swaziland', 'SZ', 'SWZ', '£'],
					  ['Sweden', 'SE', 'SWE', '€'],
					  ['Switzerland', 'CH', 'CHE', 'CHF'],
					  ['Syrian Arab Republic', 'SY', 'SYR', '£'],
					  ['Taiwan, Province of China', 'TW', 'TWN', 'NT$'],
					  ['Tajikistan', 'TJ', 'TJK', '฿'],
					  ['Tanzania, United Republic of', 'TZ', 'TZA', 'x/y'],
					  ['Thailand', 'TH', 'THA', '฿'],
					  ['Togo', 'TG', 'TGO', '$'],
					  ['Tonga', 'TO', 'TON', '฿'],
					  ['Trinidad and Tobago', 'TT', 'TTO', 'TT$'],
					  ['Tunisia', 'TN', 'TUN', '฿'],
					  ['Turkey', 'TR', 'TUR', '₤'],
					  ['Turkmenistan', 'TM', 'TKM', '฿'],
					  ['Uganda', 'UG', 'UGA', '₴'],
					  ['Ukraine', 'UA', 'UKR', '₴'], 
					  ['United Arab Emirates', 'AE', 'ARE', 'AED'],
					  ['United Kingdom', 'GB', 'GBR', '£'],
					  ['United States', 'US', 'USA', '$'],
					  ['United States Minor Outlying Islands', 'UM', 'UMI', '$'],
					  ['Uruguay', 'UY', 'URY', '$U'],
					  ['Uzbekistan', 'UZ', 'UZB', 'лв'],
					  ['Vanuatu', 'VU', 'VUT', '₫'],
					  ['Venezuela', 'VE', 'VEN', 'Bs'],
					  ['Vietnam', 'VN', 'VNM', '₫'],
					  ['Virgin Islands (British)', 'VG', 'VGB', '$'],
					  ['Virgin Islands (U.S.)', 'VI', 'VIR', '$'],
					  ['Western Sahara', 'EH', 'ESH', 'Ls'],
					  ['Yemen', 'YE', 'YEM', '﷼'],
					  ['Zambia', 'ZM', 'ZMB', 'S'],
					  ['Zimbabwe', 'ZW', 'ZWE', 'Z$'] ].each do |data|
					  if Country.where(code: data[1]).count == 0
					    Country.create!(name: data[0], 
					    								code: data[1], 
					    								a3code: data[2], 
					    								currency: data[3])
					  	puts "Created country #{data[0]}, #{data[1]}, #{data[2]}, #{data[3]}"
					  else
					  	puts "Country with code #{data[1]} already exists."
					  end
					end
				end
				
			end

		end
	end
end
